// The level set, validated when the app loads (and in tests): the 48 main levels in order,
// then the step-down siblings. levelStats.json holds each level's measured difficulty for
// the parent preview (generated by `npm run levels`, checked in CI).

import data from './levels.json';
import stats from './levelStats.json';
import { type Level, isSibling, validateLevel } from './level';

/** Main levels and siblings. */
export const ALL_LEVELS: readonly Level[] = data as Level[];
/** The 48 main levels, in order. */
export const LEVELS: readonly Level[] = ALL_LEVELS.filter((l) => !isSibling(l));
export const SIBLINGS: readonly Level[] = ALL_LEVELS.filter(isSibling);

const problems = ALL_LEVELS.flatMap(validateLevel);
if (problems.length > 0) throw new Error(`Invalid levels:\n${problems.join('\n')}`);

export const LEVEL_COUNT = LEVELS.length;

export interface LevelStats {
  board: string;
  minLen: number;
  distractors: number;
  planDepth: number;
  detour: number;
  solutions: number;
}
export const LEVEL_STATS = stats as Record<string, LevelStats>;

export function levelById(id: string): Level | undefined {
  return ALL_LEVELS.find((l) => l.id === id);
}

export function levelIndex(id: string): number {
  return LEVELS.findIndex((l) => l.id === id);
}

/** Preview order: every main level, each followed by its sibling (if any). */
export const PREVIEW_ORDER: readonly Level[] = LEVELS.flatMap((l) => [l, ...SIBLINGS.filter((s) => s.siblingOf === l.id)]);
