// The v4 level set (P01–P40, chapters that shipped), validated when the app loads and in
// tests. levelStats4.json holds each level's measured difficulty for the parent preview
// (generated by `npm run levels4`, checked in CI).

import data from './levels4.json';
import stats from './levelStats4.json';
import { type Level, ALL_OPENINGS, SIDES, TERRAIN_CHARS, boardOf, cellOf, orientationsFor, terrainAccepts, terrainAt } from './level';
import { inBounds, step } from './grid';
import { type ProgLevel, canRun, grammarProblems, levelView, parseProgram, runProgram } from './program';

/** Returns a list of problems; empty means the level is well-formed. */
export function validateProgLevel(pl: ProgLevel): string[] {
  const errs: string[] = [];
  const e = (m: string) => errs.push(`${pl.id}: ${m}`);
  if (!/^P\d{2}$/.test(pl.id)) e('bad id');
  if (!(pl.chapter >= 1 && pl.chapter <= 8)) e('bad chapter');
  if (!['practice', 'debug', 'finale'].includes(pl.kind)) e('bad kind');
  const rows = pl.grid.length;
  const cols = pl.grid[0]?.length ?? 0;
  if (rows < 1 || rows > 6 || cols < 1 || cols > 6) e(`board ${cols}x${rows} out of range`);
  if (pl.grid.some((r) => r.length !== cols)) e('grid is not rectangular');
  const chars = pl.grid.join('');
  for (const ch of chars) if (!(ch in TERRAIN_CHARS)) e(`illegal char ${ch}`);
  if (chars.split('A').length !== 2) e('needs exactly one A');
  if (chars.split('B').length !== 2) e('needs exactly one B');
  if (pl.commands !== 'absolute' && pl.commands !== 'relative') e('bad commands');
  if (!Number.isInteger(pl.slots) || pl.slots < 1 || pl.slots > 12) e('bad slots');
  if (!Number.isInteger(pl.fslots) || pl.fslots < 0 || pl.fslots > 4) e('bad fslots');
  if ((pl.kind === 'debug') !== (pl.given !== undefined)) e('debug levels (and only they) have a given program');
  if (errs.length) return errs;

  const v: Level = levelView(pl);
  const b = boardOf(v);
  const size = { cols, rows };
  if (!SIDES.includes(pl.start.exit) || !inBounds(step(b.start, b.startExit), size)) e('bad start exit');
  if (!SIDES.includes(pl.depot.entry) || !inBounds(step(b.depot, b.depotEntry), size)) e('bad depot entry');
  const stationCells = new Set<string>();
  pl.grid.forEach((row, y) => [...row].forEach((ch, x) => ch === 'S' && stationCells.add(`${x},${y}`)));
  const declared = new Set((pl.stations ?? []).map((s) => `${s.at[0]},${s.at[1]}`));
  if (stationCells.size !== declared.size || [...stationCells].some((k) => !declared.has(k))) e('stations do not match S cells');
  const orders = (pl.stations ?? []).map((s) => s.order);
  if (orders.some((o) => o !== undefined)) {
    const want = orders.map((_, i) => i + 1);
    if (orders.some((o) => o === undefined) || [...orders].sort().join() !== want.join()) e('station orders must be 1..n, on every station or none');
  }
  for (const p of pl.fixed ?? []) {
    const c = cellOf(p.at);
    if (!inBounds(c, size)) {
      e('fixed piece off the board');
      continue;
    }
    if (!ALL_OPENINGS.includes(p.openings) || !orientationsFor(p.piece).includes(p.openings)) e(`fixed ${p.piece} cannot have ${p.openings}`);
    if (!terrainAccepts(terrainAt(v, c), p.piece)) e('fixed piece on wrong terrain');
    if (p.oneWay !== undefined && !p.openings.includes(p.oneWay)) e(`one-way side ${p.oneWay} is not an opening`);
  }
  for (const [name, src] of [['solution', pl.solution], ['given', pl.given]] as const) {
    if (src === undefined) continue;
    try {
      const prog = parseProgram(src);
      for (const g of grammarProblems(pl, prog)) e(`${name}: ${g}`);
      if (!canRun(pl, prog)) e(`${name} does not fill the rows`);
      else if (name === 'solution' && !runProgram(pl, prog).success) e('solution fails');
      else if (name === 'given' && runProgram(pl, prog).success) e('given program already works');
    } catch (err) {
      e(`${name}: ${(err as Error).message}`);
    }
  }
  return errs;
}

export const LEVELS_V4: readonly ProgLevel[] = data as ProgLevel[];

const problems = LEVELS_V4.flatMap(validateProgLevel);
if (problems.length > 0) throw new Error(`Invalid v4 levels:\n${problems.join('\n')}`);

export const LEVEL_COUNT_V4 = LEVELS_V4.length;

export interface LevelStats4 {
  board: string;
  commands: string;
  slots: number;
  fslots: number;
  routeLen: number;
  solutions: number;
  guessRatio: number;
}
export const LEVEL_STATS_V4 = stats as Record<string, LevelStats4>;

export const levelById4 = (id: string) => LEVELS_V4.find((l) => l.id === id);
export const levelIndex4 = (id: string) => LEVELS_V4.findIndex((l) => l.id === id);
